In [101]:
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../")
from Myenviroments.gridWorld import GridWorldEnv
import gym

In [102]:
env = GridWorldEnv()

In [103]:
def policyEvaluation(policy,enviroment,theta=0.00001,discountFactor=1.0):
    """ 
    #TODO:  add description
    """
    #initialize V(s)
    V = np.zeros(enviroment.nS)

    while True:
        delta = 0

        for s in range(enviroment.nS):
            v = V[s]
            s1 = 0
            #first sumatory
            for a in range(enviroment.nA):
                for p,nextS,reward,don in enviroment.P[s][a]:
                    s1 += p *  (reward + discountFactor * V[nextS])
            #second sumatory
            for a, pi in enumerate(policy[s]):
                V[s] = pi * s1

            # how much our V have change
            delta = max(delta,np.abs(v - V[s]))

        if delta < theta:
            break

    V = np.array(V)
    return V

In [104]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policyEvaluation(random_policy, env)
print("value function:")
print(v.reshape(env.shape))

value function:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]
